### ISSUE TITLE
Update "latest" release version

### ISSUE THREAD

**Issue by adamkrawczyk** [eclipse-zenoh/zenoh-backend-influxdb#301]
### Expected behavior
- latest points to `1.1.0` 

### Actual behavior
- latest points to `1.0.0` 

### Description

Seems like the tag lates is not updated per release as it supposed to be. Here is the current state.

here is the newest (supposed to be latest) influx `1.1.0` release: 
https://download.eclipse.org/zenoh/zenoh-backend-influxdb/1.1.0/

latest (still linked to `1.0.0`) : 
https://download.eclipse.org/zenoh/zenoh-backend-influxdb/latest/

**Comment by JEnoch** [comment]
Thanks for your report! It has been fixed today.
