### ISSUE TITLE
Token based authentication

### ISSUE THREAD

**Issue by kydos** [eclipse-zenoh/zenoh-backend-influxdb#35]
### Describe the feature

It would be quite useful to support token based authentication. This seems to be supported by the rust-api (see https://docs.rs/influxdb/latest/influxdb/struct.Client.html#method.with_token) and would work more nicely with influx-db docker images which by default have authentication based on user/passwd disabled. 

In general the token used by influx-db API is available on the `INFLUXDB_TOKEN` environment variable.

**Comment by Mallets** [comment]
@snehilzs does #4 also cover this issue?
