### ISSUE TITLE
[Bug] Duplicate replies on get with time filter

### ISSUE THREAD

**Issue by JEnoch** [eclipse-zenoh/zenoh-backend-influxdb#39]
### Describe the bug

On a query with a time filter, an InfluxDB storage returns duplicates for each reply.

### To reproduce

1. Run InfluxDB, then `zenohd` with this conf:
```json5
plugins: {
  storage_manager: {
    volumes: {
      influxdb: {
        url: "http://localhost:8086",
      }
    },
    storages: {
      demo: {
        key_expr: "demo/example/**",
        volume: {
          id: "influxdb",
          db: "zenoh_example",
          create_db: true,
          on_closure: "drop_db",
        }
      }
    }
  }
}
```
2. Run the `z_pub` example for 3 seconds (i.e. 3 publications)
3. Run the `z_get`example as such:
  `z_get -s "demo/**?_time=[..]"`

Expected result: 3 replies with number 0, 1 and 2
Actual result: 9 replies, 3 for each number

### System info

Zenoh v0.7.2-rc

**Comment by Mallets** [comment]
Fixed by https://github.com/eclipse-zenoh/zenoh-backend-influxdb/pull/40
