### ISSUE TITLE
InfluxDB2.0 Support

### ISSUE THREAD

**Issue by Jayclifford345** [eclipse-zenoh/zenoh-backend-influxdb#4]
Hi there,
Does the plugin currently support InfluxDB2.0? The move to Influx2.0 changed serval key architectures:
- Access to the InfuxDB2.0 is now by default token-based
- Shift from DB to buckets and organization.

InfluxDB2.0 does support legacy commands is this something you are already using? I am just struggling to get the example working with Influx2.0.

Many thanks for your suppoirt.

**Comment by JEnoch** [comment]
Hi @Jayclifford345 ,
Unfortunately, the InfluxDB Rust library we depend on doesn't yet support InfluxDB 2.0.
It has an open issue for this: influxdb-rust/issues#56.

**Comment by Jayclifford345** [comment]
Many thanks for your reply @JEnoch . We will look forward to the release when Influx implements their Rust Client Libary.  I also anticipate  Influx IOx will be of great interest to Zenoh when further developed:

https://www.influxdata.com/blog/announcing-influxdb-iox/

**Comment by clibequilibrium** [comment]
@JEnoch I think https://lib.rs/crates/influxdb2 is what you might be looking for based on https://github.com/influxdb-rs/influxdb-rust/issues/56#issuecomment-1247009992

**Comment by clibequilibrium** [comment]
There is one with v2 and v1.8 API compatability. 

https://github.com/bonitoo-io/influxdb-client-rust
